# Generated by Django 4.2.7 on 2023-11-25 20:47

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Photo de profil')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('presentation', models.TextField(blank=True, null=True, verbose_name='Présentation')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
            ],
            options={
                'verbose_name': 'Profil',
                'ordering': ['registration_date'],
            },
        ),
    ]
