# Generated by Django 4.2.7 on 2024-02-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/', verbose_name='Photo de profil')),
                ('first_name', models.CharField(max_length=50, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('presentation', models.TextField(blank=True, null=True, verbose_name='Présentation')),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('skin_brightness', models.FloatField(blank=True, null=True, verbose_name='Luminosité de la peau')),
                ('skin_info', models.TextField(blank=True, null=True, verbose_name='Couleur de peau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
                'ordering': ['registration_date'],
            },
        ),
    ]
