# Generated by Django 4.2.7 on 2023-11-25 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skin_brightness',
            field=models.FloatField(blank=True, null=True, verbose_name='Luminosité de la peau'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skin_info',
            field=models.TextField(blank=True, null=True, verbose_name='Couleur de peau'),
        ),
    ]
